### ISSUE TITLE
Requests and Current issue

### ISSUE THREAD

**Issue by thipokKub** [burin-n/db-backend#1]
Here are some issues I have found
- Cannot navigate to wiki tab (How I suppose to develop frontend out of this >:-[ )
- No user login implemented (token or api)
- No Withdrawn functionality
- No GPAX score
- No personal information
- No "Room" scheduler
- The README is terrible, no document or whatsoever. Little to no comments exist in the code.
- Pretty much lack a lot of stuff :-P

Current code is using async function but without the use of "try-catch" so whenever the function failed, nothing is returned. This is frustrating, please fix.

Please change serving port from 3000 to something else, it collide with frontend website while I'm testing.

# @burin-n

**Comment by thipokKub** [comment]
get subject detail should also require semester and year to classify which subject is open for what semester.

**Comment by burin-n** [comment]
https://www.getpostman.com/collections/e1fdc4f60099faa402fb
